# Generated by Django 5.2 on 2025-05-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
